[phases.setup]
nixPkgs = ["nodejs"]

[phases.build]
cmds = [
    "cd backend && npm install && npm run build",
    "cd frontend && npm install &&npm run build || true"
]

[start]
cmd = "node dist/src/server.js"