[phases.setup]
nixPkgs = ["nodejs", "git", "caddy"]

[phases.build]
cmds = [
    "cd backend && npm install && npm run build",
    "cd frontend && npm install &&npm run build || true"
]

[start]
cmd = "sh -c 'node dist/src/server.js  & exec caddy run --config /assets/Caddyfile --adapter caddyfile 2>&1'"
